---
title: "Untitled"
output: html_document
date: '2023-11-30'
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(readxl) 
library(janitor)
library(viridis)
library(scales)
library(ggrepel)
library(flextable)
library(sf)
library(plotly)
library(patchwork)
library(ggsflabel)
library(rKenyaCensus)

options(scipen = 100)

`%out%` <- Negate(`%in%`)

sf_use_s2(FALSE)

# Fixing dates
name_to_date <- function(x) {
  lubridate::mdy(ifelse(x %in% c(month.name, month.abb), paste0(x, "/01/2023"), x))
}

```

# Locations

```{r}
locations <- read_xlsx("./data/ken_adminboundaries_tabulardata_v2.xlsx", 
                       sheet = "ADM2") %>% 
  clean_names() %>%
  mutate(adm2alt1_en = ifelse(adm2_pcode == "KE033177", "Transmara East", adm2alt1_en), 
         adm2alt2_en = ifelse(adm2_pcode == "KE033177", "Transmara West", adm2alt2_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE002010", "Samburu", adm2alt1_en), 
         adm2alt1_en = ifelse(adm2_pcode == "KE007027", "Garissa Township", adm2alt1_en), 
         adm2alt2_en = ifelse(adm2_pcode == "KE010048", "Loyangalani", adm2alt2_en), 
         adm2alt1_en = ifelse(adm2_pcode == "KE010046", "Chalbi", adm2alt1_en), 
         adm2alt1_en = ifelse(adm2_pcode == "KE039220", "Bungoma South", adm2alt1_en), 
         adm2alt1_en = ifelse(adm2_pcode == "KE039224", "Bungoma North", adm2alt1_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE039224", "Bungoma North", adm2alt1_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE007031", "Hulugho", adm2alt1_en), 
         adm2alt1_en = ifelse(adm2_pcode == "KE003012", "Chonyi", adm2alt1_en), 
         adm2alt1_en = ifelse(adm2_pcode == "KE003015", "Kauma", adm2alt1_en), 
         adm2alt1_en = ifelse(adm2_pcode == "KE006024", "Taita", adm2alt1_en), 
         adm2alt2_en = ifelse(adm2_pcode == "KE008033", "Buna", adm2alt2_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE009042", "Kutulo", adm2alt1_en), 
         adm2alt2_en = ifelse(adm2_pcode == "KE009042", "Mandera Central", adm2alt2_en), 
         adm2alt2_en = ifelse(adm2_pcode == "KE010046", "Marsabit North", adm2alt2_en), 
         adm2alt2_en = ifelse(adm2_pcode == "KE011049", "Isiolo", adm2alt2_en), 
         adm2alt1_en = ifelse(adm2_pcode == "KE012056", "Imenti North", adm2alt1_en), 
         adm2alt1_en = ifelse(adm2_pcode == "KE012059", "Imenti South", adm2alt1_en), 
         adm2alt1_en = ifelse(adm2_pcode == "KE012058", "Meru Central", adm2alt1_en), 
         adm2alt1_en = ifelse(adm2_pcode == "KE012057", "Buuri East", adm2alt1_en),
         adm2alt2_en = ifelse(adm2_pcode == "KE012057", "Buuri West", adm2alt2_en), 
         adm2alt1_en = ifelse(adm2_pcode == "KE012055", "Tigania Central", adm2alt1_en), 
         adm2alt1_en = ifelse(adm2_pcode == "KE023123", "Kibish", adm2alt1_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE019099", "Nyeri Central", adm2alt1_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE019098", "Mukurwe-ini", adm2alt1_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE019095", "Kieni East", adm2alt1_en),
         adm2alt2_en = ifelse(adm2_pcode == "KE019095", "Kieni West", adm2alt2_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE019096", "Mathira East", adm2alt1_en),
         adm2alt2_en = ifelse(adm2_pcode == "KE019096", "Mathira West", adm2alt2_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE020101", "Kirinyaga East", adm2alt1_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE020102", "Kirinyaga West", adm2alt1_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE020100", "Mwea East", adm2alt1_en),
         adm2alt2_en = ifelse(adm2_pcode == "KE020100", "Mwea West", adm2alt2_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE013060", "Nithi", adm2alt1_en), 
         adm2alt1_en = ifelse(adm2_pcode == "KE013062", "Tharaka North", adm2alt1_en),
         adm2alt2_en = ifelse(adm2_pcode == "KE013062", "Tharaka South", adm2alt2_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE014065", "Mbeere South", adm2alt1_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE014066", "Mbeere North", adm2alt1_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE014066", "Mbeere North", adm2alt1_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE015074", "Ikutha", adm2alt1_en),
         adm2alt2_en = ifelse(adm2_pcode == "KE015074", "Katulani", adm2alt2_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE015071", "Kisasi", adm2alt1_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE015067", "Kyuso", adm2alt1_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE015067", "Kyuso", adm2alt1_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE015067", "Migwani", adm2alt1_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE016080", "Athi River", adm2alt1_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE016081", "Kalama", adm2alt1_en), 
         adm2alt2_en = ifelse(adm2_pcode == "KE016081", "Machakos", adm2alt2_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE017086", "Kathonzweni", adm2alt1_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE017083", "Mbooni East", adm2alt1_en),
         adm2alt2_en = ifelse(adm2_pcode == "KE017083", "Mbooni West", adm2alt2_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE017085", "Kilungu", adm2alt1_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE017087", "Makindu", adm2alt1_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE017084", "Mukaa", adm2alt1_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE017086", "Nzaui", adm2alt1_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE024131", "Pokot North", adm2alt1_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE025133", "Samburu Central", adm2alt1_en), 
         adm2alt1_en = ifelse(adm2_pcode == "KE026140", "Trans Nzoia East", adm2alt1_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE026137", "Trans Nzoia West", adm2alt1_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE030157", "East Pokot", adm2alt1_en),
         adm2alt2_en = ifelse(adm2_pcode == "KE030157", "Tiaty East", adm2alt2_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE030162", "Koibatek", adm2alt1_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE030162", "Koibatek", adm2alt1_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE033178", "Transmara East", adm2alt1_en),
         # Only because Kilgoris was formerly in the former Transmara District
         adm2alt1_en = ifelse(adm2_pcode == "KE033177", "Transmara West", adm2alt1_en), 
         adm2alt2_en = ifelse(adm2_pcode == "KE033177", NA_character_, adm2alt2_en), 
         adm2alt1_en = ifelse(adm2_pcode == "KE013061", "Igambang'ombe", adm2alt1_en),
         adm2alt2_en = ifelse(adm2_pcode == "KE013060", "Meru South", adm2alt2_en),
         adm2alt2_en = ifelse(adm2_pcode == "KE017086", "Kathonzweni", adm2alt2_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE017088", "Kibwezi", adm2alt1_en),
         adm2alt2_en = ifelse(adm2_pcode == "KE034187", "Loitokitok", adm2alt2_en), 
         adm2alt2_en = ifelse(adm2_pcode == "KE034186", "Mashuuru", adm2alt2_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE039218", "Bungoma Central", adm2alt1_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE039221", "Bungoma East", adm2alt1_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE039223", "Kimilili-Bungoma", adm2alt1_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE047280", "Njiru", adm2alt1_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE047277", "Lang'ata", adm2alt1_en), 
         adm2alt2_en = ifelse(adm2_pcode == "KE024131", "North Pokot", adm2alt2_en), 
         adm2alt1_en = ifelse(adm2_en == "Baringo South", "Marigat", adm2alt1_en), 
         adm2alt1_en = ifelse(adm2_en == "Baringo Central", NA_character_, adm2alt1_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE024130", "Pokot Central", adm2alt1_en),
         adm2alt1_en = ifelse(adm2_pcode == "KE024129", NA_character_, adm2alt1_en)) %>% 
  mutate(adm2alt1_en = ifelse(adm2_pcode == "KE008036", NA_character_, adm2alt1_en)) %>% 
  filter(!is.na(adm2_pcode))


pcode2_shape <- 
  sf::st_read("./data/ken_adm_iebc_20191031_shp/ken_admbnda_adm2_iebc_20191031.shp", 
          quiet = TRUE) %>% 
  clean_names() %>% 
  st_as_sf() %>%
  mutate(fo = case_when(adm1_en %in% c("Samburu", "Turkana", "West Pokot", "Baringo") ~ "Lodwar", 
                        adm1_en %in% c("Garissa", "Isiolo", "Mandera", "Marsabit", "Tana River", "Wajir") ~ "Garissa", 
                        adm1_en %in% c("Bungoma", "Narok") ~ "Kisumu", 
                        adm1_en %in% c("Nairobi", "Kilifi", "Kwale", "Kajiado") ~ "Nairobi"))


pcode1_shape <- 
  sf::st_read("./data/ken_adm_iebc_20191031_shp/ken_admbnda_adm1_iebc_20191031.shp", 
          quiet = TRUE) %>% 
  clean_names()

adm2 <- partner_admin2 %>%
  mutate(sub_county = trimws(sub_county), 
         county = trimws(county)) %>% 
  mutate(sub_county = str_replace_all(sub_county, "Lungalunga", "Lunga Lunga"),
         sub_county = str_replace_all(sub_county, "Kauma", "Ganze"), 
         sub_county = str_replace_all(sub_county, "Garissa town", "Garissa Township"), 
         sub_county = ifelse(sub_county == "Garissa", "Garissa Township", sub_county), 
         sub_county = str_replace_all(sub_county, "Kamkunji", "Kamukunji"), 
         sub_county = str_replace_all(sub_county, "Garbatula", "Garbatulla"),
         sub_county = str_replace_all(sub_county, "Pokot North", "North Pokot"),
         sub_county = str_replace_all(sub_county, "Hulogho", "Hulugho"), 
         sub_county = str_replace_all(sub_county, "Cenral", "Central"), 
         sub_county = ifelse(sub_county == "Tiaty East" & county == "Baringo", 
                             "Tiaty", 
                             sub_county),
         sub_county = ifelse(sub_county == "Bungoma West (sirisia)" & county == "Bungoma", 
                             "Sirisia", 
                             sub_county), 
         sub_county = ifelse(str_detect(sub_county, "Dagoreti") & county == "Nairobi", 
                             "Dagoretti", 
                             sub_county), 
         sub_county = ifelse(sub_county == "Central" & county == "Samburu", 
                             "Samburu Central",
                             sub_county)) %>% 
  filter(sub_county %out% c("Chonyi", "Isiolo")) %>% 
  left_join(locations %>%
              distinct(adm1_en, adm1_pcode), 
            by = c("county" = "adm1_en")) %>%
  left_join(locations %>%
              select(adm2_en, adm2_pcode_a = adm2_pcode, adm1_en), 
            by = c("sub_county" = "adm2_en", 
                   "county" = "adm1_en")) %>% 
  left_join(locations %>%
              select(adm2alt1_en, adm2_pcode_b = adm2_pcode, adm1_en), 
            by = c("sub_county" = "adm2alt1_en", 
                   "county" = "adm1_en")) %>% 
  left_join(locations %>%
              select(adm2alt2_en, adm2_pcode_c = adm2_pcode, adm1_en), 
            by = c("sub_county" = "adm2alt2_en", 
                   "county" = "adm1_en")) %>% 
  mutate(adm2_pcode = coalesce(adm2_pcode_a, adm2_pcode_b, adm2_pcode_c)) %>% 
  mutate(# Persistent problem
         adm2_pcode = ifelse(sub_county == "Transmara West", 
                             "KE033177", 
                             adm2_pcode), 
         adm2_pcode = ifelse(sub_county == "Transmara East", 
                             "KE033177", 
                             adm2_pcode)) %>% 
  select(-adm2_pcode_a, -adm2_pcode_b, -adm2_pcode_c) %>% 
  left_join(locations %>% select(adm2_en, adm2_pcode), 
            by = "adm2_pcode") %>% 
  mutate(constituency = ifelse(!is.na(adm2_pcode), 
                             adm2_en, 
                             sub_county)) %>% 
  select(-adm2_en) %>% 
  # Pull out this list to send back to UNICEF for verification
  # filter(is.na(adm2_pcode))
  distinct(county, constituency, partner, adm1_pcode, adm2_pcode) %>% 
  mutate(partner = trimws(partner), 
         partner = ifelse(partner == "Life Skills Promoters (LISP)", "LISP", partner)) %>% 
  mutate(fo = case_when(county %in% c("Samburu", "Turkana", "West Pokot", "Baringo") ~ "Lodwar", 
                        county %in% c("Garissa", "Isiolo", "Mandera", "Marsabit", "Tana River", "Wajir") ~ "Garissa", 
                        county %in% c("Bungoma", "Narok") ~ "Kisumu", 
                        county %in% c("Nairobi", "Kilifi", "Kwale", "Kajiado") ~ "Nairobi")) %>% 
  mutate(partner = ifelse(partner == "Fin Church Aid (FCA)", "Finn Church Aid", partner), 
         adm2_pcode = ifelse(constituency == "Kipkomo", "KE024129", adm2_pcode), 
         constituency = ifelse(adm2_pcode == "KE024129", "Kapenguira", constituency
                               )) %>% 
  filter(!is.na(constituency))
  
adm1 <- adm2 %>% 
  distinct(county, partner, adm1_pcode, fo)  

all_towns_shape <- 
  sf::st_read("./data/kenya_all_towns/kenya_all_towns_eeTVhKM.shp", 
          quiet = TRUE) %>% 
  clean_names() %>% 
  st_as_sf() %>%
           filter(town_type %in% c("City", "Municipality", "Township/Town", "Trading Centre"))

census_sub_counties <- V4_T1.9 %>% 
  clean_names() %>% 
  mutate(sub_county_pcode = paste0("KEN_", county_code, "_", sub_county_code)) %>% 
  mutate_at(vars(county, sub_county),
              ~ str_to_title(.)) %>%
    mutate(county = str_replace_all(county, "/", "-"), 
           county = str_replace_all(county, "Taita-Taveta", "Taita Taveta"), 
           county = str_replace_all(county, "\\sCity", "")) %>% 
    mutate(sub_county =
             str_replace_all(sub_county,
                             c("Lunga Lunga" = "Lungalunga",
                               "Mukurwe-Ini" = "Mukurwe-ini", 
                               "Kimilili" = "Kimilili-Bungoma", 
                               "Kotulo" = "Kutulo",
                               "Mt Elgon Forest" = "Mt Elgon")), 
           sub_county = ifelse(county == "Kwale" & sub_county == "Samburu", 
                               "Samburu-Kwale", 
                               sub_county)) 

poverty <- read_csv("./data/poverty_chart.csv") %>% 
  `colnames<-`(c("county", "poverty_incidence", "distribution_of_poor", 
                 "poverty_gap", "severity_of_poverty", "population", "number_of_poor")) %>% 
  mutate(county = str_replace_all(county, "Taita/Taveta", "Taita Taveta"), 
         county = str_replace_all(county, "Elgeyo/Marakwet", "Elgeyo-Marakwet"), 
         county = str_replace_all(county, "Nairobi City", "Nairobi")) %>% 
  left_join(locations %>% 
              distinct(adm1_en, adm1_pcode), 
            by = c("county" = "adm1_en")) 
  
```


# Census

```{r}
clean_census_adm2_incomplete <- function(tbl) {
  
  tbl %>% 
  mutate(constituency = ifelse(admin_area == "SubCounty", 
                               sub_county, 
                               NA_character_)) %>% 
  mutate(county = str_remove_all(county, "\\sCounty"),
         county = str_replace_all(county, "\\/", "\\-"),
         county = str_replace_all(county, "Taita-Taveta", "Taita Taveta"), 
         county = str_replace_all(county, "Nairobi City", "Nairobi"),
         constituency = str_remove_all(constituency, "\\*"), 
         constituency = str_replace_all(constituency, "Mt", "Mt."), 
         constituency = str_replace_all(constituency, "Garissa", "Garissa Township"), 
         constituency = str_replace_all(constituency, "Loiyangalani", "Loyangalani"), 
         constituency = str_replace_all(constituency, "Banisa", "Banissa"), 
         constituency = str_replace_all(constituency, "Habaswein", "Habasweine"), 
         constituency = str_replace_all(constituency, "Lungalunga", "Lunga Lunga"), 
         constituency = str_replace_all(constituency, "Samburu-Kwale", "Kinango"),
         constituency = str_replace_all(constituency, "Trans Mara", "Transmara")) %>% 
  left_join(locations %>%
              select(adm2_en, adm2_pcode_a = adm2_pcode, adm1_en), 
            by = c("constituency" = "adm2_en", 
                   "county" = "adm1_en")) %>% 
  left_join(locations %>%
              select(adm2alt1_en, adm2_pcode_b = adm2_pcode, adm1_en), 
            by = c("constituency" = "adm2alt1_en", 
                   "county" = "adm1_en")) %>% 
  left_join(locations %>%
              select(adm2alt2_en, adm2_pcode_c = adm2_pcode, adm1_en), 
            by = c("constituency" = "adm2alt2_en", 
                   "county" = "adm1_en")) %>% 
  left_join(locations %>% 
              distinct(adm1_en, adm1_pcode), 
            by = c("county" = "adm1_en")) %>% 
  mutate(adm2_pcode = coalesce(adm2_pcode_a, adm2_pcode_b, adm2_pcode_c)) %>% 
  filter(admin_area == "SubCounty") %>% 
  mutate(adm2_pcode = ifelse(constituency == "Kipkomo", "KE024129", adm2_pcode), 
         adm2_pcode = ifelse(constituency == "Transmara East", "KE033178", adm2_pcode)) %>% 
  mutate(fo = case_when(county %in% c("Samburu", "Turkana", "West Pokot", "Baringo") ~ "Lodwar", 
                        county %in% c("Garissa", "Isiolo", "Mandera", "Marsabit", "Tana River", "Wajir") ~ "Garissa", 
                        county %in% c("Bungoma", "Narok") ~ "Kisumu", 
                        county %in% c("Nairobi", "Kilifi", "Kwale", "Kajiado") ~ "Nairobi")) %>%
  select(-c(adm2_pcode_a, adm2_pcode_b, adm2_pcode_c)) 
  
}
```

## School-aged children

```{r}
adm2_school_aged_children <- V3_T2.3 %>% 
  clean_names() %>% 
  mutate_at(vars(county, sub_county), ~ str_to_title(.x)) %>% 
  mutate(admin_area = "SubCounty", 
         county = str_replace_all(county, "Taita/ Taveta", "Taita Taveta")) %>% 
  filter(age %in% c("0 - 4", "5-9", "10 -14", "15", "16", "17") & 
           sub_county != "All") %>% 
  mutate(age = str_replace_all(age, "\\s-\\s", "-"), 
         age = str_replace_all(age, "\\s-", "-")) %>% 
  mutate(age = trimws(age)) %>% 
  mutate(age_bracket = case_when(
    age == "0-4" ~ "0_4", 
    age == "5-9" ~ "5_9", 
    age == "10-14" ~ "10_14", 
    age %in% c("15", "16", "17") ~ "15_17"
  )) %>% 
  group_by(county, sub_county, age_bracket, admin_area) %>% 
  summarise(male = sum(male), 
            female = sum(female), 
            total = sum(total), 
            .groups = "drop") %>% 
  clean_census_adm2_incomplete() %>% 
  mutate(age_bracket = fct_relevel(factor(age_bracket), c("0_4", "5_9", "10_14", "15_17"))) %>% 
  arrange(county, sub_county, age_bracket) %>%
  mutate(constituency = trimws(str_remove(constituency, "\\.")), 
         constituency = ifelse(constituency == "Mt. Kenya Fore", 
                               "Mt. Kenya Forest", 
                               constituency), 
         sub_county = str_replace_all(sub_county, 
                                        c("Lunga Lunga" = "Lungalunga",
                                          "Mukurwe-Ini" = "Mukurwe-ini", 
                                          "Kimilili" = "Kimilili-Bungoma", 
                                          "Kotulo" = "Kutulo",
                                          "Mt Elgon Forest" = "Mt Elgon", 
                                          "Mukurweini" = "Mukurwe-ini"
                                          )), 
         sub_county = ifelse(county == "Kwale" & sub_county == "Samburu", 
                               "Samburu-Kwale", 
                               sub_county)) %>%
  left_join(
  census_sub_counties %>%
    select(county, sub_county, sub_county_pcode), 
                                     by = c("county", "sub_county")) %>% 
  filter(!is.na(sub_county_pcode))
```


## Census adm2 incomplete

```{r}
# Pcodes have been incompletely matched against the census. Only counties and constituencies relevant to 
# Operation Come to School have been matched. Much additional work is required. 

census_adm2_incomplete <- V1_T2.6 %>% 
  clean_names() %>% 
  clean_census_adm2_incomplete() %>% 
  left_join(
  census_sub_counties %>%
    select(county, sub_county, sub_county_pcode), 
                                     by = c("county", "sub_county")) %>% 
  left_join(
    adm2_school_aged_children %>%
      select(-male, -female) %>%
      pivot_wider(names_from = age_bracket, 
              names_prefix = "age_", 
              values_from = total) %>%
      select(sub_county_pcode, matches("age_")), 
    by = "sub_county_pcode"
  )


adm1_pcode_list <- adm1 %>% filter(!is.na(adm1_pcode)) %>% select(adm1_pcode) %>% as.list()
```

# Outputs

## Adm2 Targets


```{r}

adm1_list <- adm1 %>% distinct(adm1_pcode) %>% as.list()
adm2_list <- adm2 %>% distinct(adm2_pcode) %>% as.list()

adm2_targets_all_cols <- adm2 %>% 
  rbind(
    locations %>%
      filter(adm1_pcode %in% adm1_list$adm1_pcode) %>% 
    filter(adm2_pcode %out% adm2_list$adm2_pcode) %>% 
    select(county = adm1_en, adm1_pcode, constituency = adm2_en, adm2_pcode) %>% 
    mutate(fo = case_when(county %in% c("Samburu", "Turkana", "West Pokot", "Baringo") ~ "Lodwar", 
                          county %in% c("Garissa", "Isiolo", "Mandera", "Marsabit", "Tana River", "Wajir") ~ "Garissa", 
                          county %in% c("Bungoma", "Narok") ~ "Kisumu", 
                          county %in% c("Nairobi", "Kilifi", "Kwale", "Kajiado") ~ "Nairobi"), 
           partner = NA_character_)
  ) %>% 
  mutate(partner = ifelse(str_detect(constituency, "Embakasi|Roysambu|Ruaraka"), 
                          "LISP",
                          partner)) %>% 
  mutate(adm2_pcode = ifelse(constituency == "West Pokot" & county == "West Pokot", 
                             "KE024131", adm2_pcode)) %>% 
  arrange(partner) %>% 
  group_by(adm2_pcode, constituency, county, adm1_pcode, fo) %>% 
  summarise(partners = paste0(partner, collapse = ", "), 
            .groups = "keep") %>% 
  mutate(constituency = str_trim(constituency)) %>% 
  left_join(census_adm2_incomplete %>% 
              filter(!is.na(adm2_pcode)) %>% 
              select(adm2_pcode, population, number_of_households, average_household_size, 
                     matches("age_")), 
            by = c("adm2_pcode" = "adm2_pcode")) %>% 
  mutate(population = case_when(str_detect(constituency, "Embakasi") ~ 983233 / 5, 
                                str_detect(constituency, "Roysambu|Kasarani|Ruaraka") ~ 772586 / 3,
                                TRUE ~ population), 
         number_of_households = case_when(str_detect(constituency, "Embakasi") ~ 347955 / 5, 
                                          str_detect(constituency, "Roysambu|Kasarani|Ruaraka") ~ 271290 / 3,
                                          TRUE ~ number_of_households), 
         average_household_size = case_when(
           str_detect(constituency, "Embakasi") ~ 2.8,
           str_detect(constituency, "Roysambu|Ruaraka|Kasarani") ~ 2.8, 
           TRUE ~ average_household_size), 
         age_0_4 = case_when(str_detect(constituency, "Embakasi") ~ 125958 / 5, 
                                          str_detect(constituency, "Roysambu|Kasarani|Ruaraka") ~ 178350 / 3,
                                          TRUE ~ age_0_4), 
         age_5_9 = case_when(str_detect(constituency, "Embakasi") ~ 98534 / 5, 
                                          str_detect(constituency, "Roysambu|Kasarani|Ruaraka") ~ 146439 / 3,
                                          TRUE ~ age_5_9), 
         age_10_14 = case_when(str_detect(constituency, "Embakasi") ~ 80440 / 5, 
                                          str_detect(constituency, "Roysambu|Kasarani|Ruaraka") ~ 126949 / 3,
                                          TRUE ~ age_10_14), 
         age_15_17 = case_when(str_detect(constituency, "Embakasi") ~ 40796 / 5, 
                                          str_detect(constituency, "Roysambu|Kasarani|Ruaraka") ~ 66974 / 3,
                                          TRUE ~ age_15_17)) %>% 
  distinct(adm2_pcode, constituency, adm1_pcode, county, fo, partners, 
           population, number_of_households, average_household_size, 
           age_0_4, age_5_9, age_10_14, age_15_17) %>% 
  group_by(adm2_pcode, constituency, county, adm1_pcode, fo, partners) %>%
  # Consolidating the constituencies with more than one sub-county in them
  summarise(population = sum(population, na.rm = TRUE), 
            number_of_households = sum(number_of_households, na.rm = TRUE), 
            # This is to consolidate the constituencies where there are multiple sub-counties
            age_0_4 = sum(age_0_4, na.rm = TRUE), 
            age_5_9 = sum(age_5_9, na.rm = TRUE), 
            age_10_14 = sum(age_10_14, na.rm = TRUE), 
            age_15_17 = sum(age_15_17, na.rm = TRUE)) %>%
  ungroup() %>% 
  mutate(average_household_size = population / number_of_households) %>%
  mutate(n_partners = str_count(partners, ",") + 1) %>% 
  left_join(poverty %>% 
              filter(!is.na(adm1_pcode)) %>% 
              select(adm1_pcode, poverty_incidence), 
            by = "adm1_pcode") %>% 
  mutate(poor_persons = poverty_incidence / 100 * population) %>% 
  mutate(werk_total_target = ifelse(str_detect(partners, "WERK"), 40720, 0), 
         fca_total_target = ifelse(str_detect(partners, "Finn Church Aid"), 36500, 0),
         lisp_total_target = ifelse(str_detect(partners, "LISP"), 19044, 0),
         save_total_target = ifelse(str_detect(partners, "Save the Children"), 32898, 0),
         irck_total_target = ifelse(str_detect(partners, "IRCK"), 2500, 0)) %>% 
  mutate(werk_catchment = ifelse(werk_total_target != 0, 
                                            sum(poor_persons[werk_total_target != 0]), 
                                            0), 
         fca_catchment = ifelse(fca_total_target != 0, sum(poor_persons[fca_total_target != 0]), 0), 
         lisp_catchment = ifelse(lisp_total_target != 0, sum(poor_persons[lisp_total_target != 0]), 0), 
         save_catchment = ifelse(save_total_target != 0, sum(poor_persons[save_total_target != 0]), 0), 
         irck_catchment = ifelse(irck_total_target != 0, sum(poor_persons[irck_total_target != 0]), 0)) %>%
  mutate(werk_target = poor_persons / werk_catchment * werk_total_target, 
         fca_target = poor_persons / fca_catchment * fca_total_target, 
         lisp_target = poor_persons / lisp_catchment * lisp_total_target, 
         save_target = poor_persons / save_catchment * save_total_target, 
         irck_target = poor_persons / irck_catchment * irck_total_target,
         so_target = NA_integer_) %>% 
  mutate_at(vars(werk_target:irck_target), ~ ifelse(is.nan(.x), 0, .x))

adm2_targets <- adm2_targets_all_cols %>%
  mutate(children_0_17 = age_0_4 + age_5_9 + age_10_14 + age_15_17) %>% 
  select(adm1_pcode, county, adm2_pcode, constituency, fo, partners, n_partners,
         population, number_of_households, average_household_size, 
         children_0_17, poverty_incidence, poor_persons, 
         werk_target:so_target) %>% 
  # Special Olympics left out for the moment since they don't have targets
  mutate(combined_target = (werk_target + fca_target + lisp_target + save_target + irck_target)) %>% 
  mutate_at(vars(werk_target, fca_target, lisp_target, save_target, irck_target, combined_target), 
            ~ round(.))
  

```




```{r}

locations_match <- locations %>% 
  select(adm1_en, adm1_pcode, adm2_pcode, adm2_en, adm2alt1_en, adm2alt2_en) %>%
  pivot_longer(cols = c(adm2_en, 
                        adm2alt1_en, 
                        adm2alt2_en), 
               names_to = "origin", 
               values_to = "adm2_en") %>% 
  filter(!is.na(adm2_en)) %>% 
  left_join(census_adm2_incomplete %>%
              distinct(county, sub_county, sub_county_pcode),
             by = c("adm1_en" = "county", 
                    "adm2_en" = "sub_county")) %>% 
  group_by(adm2_pcode) %>% 
  fill(sub_county_pcode, .direction = c("up")) %>% 
  fill(sub_county_pcode, .direction = "down") %>% 
  ungroup()
  
```

# Export Out


```{r}

adm2_targets %>% 
  write_csv("./data/adm2_targets.csv")

adm2_targets %>% 
  write_csv("C:/Users/seanywng/Documents/R/operation_come_to_school_public/data/adm2_targets.csv")

adm2 %>% write_csv("./data/adm2_reference.csv")

adm2 %>% write_csv("C:/Users/seanywng/Documents/R/operation_come_to_school_public/data/adm2_reference.csv")

locations %>% write_csv("./data/locations.csv")

locations %>% write_csv("C:/Users/seanywng/Documents/R/operation_come_to_school_public/data/locations.csv")

locations_match %>% write_csv("./data/locations_match.csv")

locations_match %>% 
  write_csv("C:/Users/seanywng/Documents/R/operation_come_to_school_public/data/locations_match.csv")

census_adm2_incomplete %>% write_csv("C:/Users/seanywng/Documents/R/operation_come_to_school_public/data/census_adm2_incomplete.csv")

```


# Alternate sub-counties shapefile

Verification and matching needed. 

```{r}
# These shapes are supposedly subcounties, 
# Some work will be needed to help them match pcodes even from the census
shape_alt <- sf::st_read("./data/ke_subcounty/ke_subcounty.shp", 
                         quiet = TRUE)

shape_alt %>%
  ggplot() + 
  geom_sf(size = .1)
```